### ISSUE TITLE
Release dySEM 1.0.0

### ISSUE THREAD

**Issue by jsakaluk** [jsakaluk/dySEM#101]
First release:

* [x] update unit tests for scriptCFA lvariance and lmean 
* [x] update vignette code using scriptCFA()
* [x] create df counting diagrams + unit tests for residual, lvariance (extended from loading invariance), and lmean (extended from intercept invariance) for dyadic CFA
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `git push`
* [x] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `git push`
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] `git push`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by omarjcamanto** [comment]
**Check that all exported functions have @return and @examples**
- I can confirm that all exported functions have @return (and all non-exported functions have @nord).
- I can also confirm that all exported functions have @examples.


**Check that Authors@R: includes a copyright holder (role 'cph')**
- checks out.


**Review https://github.com/DavisVaughan/extrachecks** 
- PR #105 addresses this.


**urlchecker::url_check()**
- The urlchecker::url_check() returns complains about the CRAN badge URL (which makes sense of course) and URL to [Sakaluk, Fisher, & Kilshaw](https://doi.org/10.1111/pere.12341) (2021) in the README. But perhaps these might be safe to ignore because `rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"))` and `devtools::check(remote = TRUE, manual = TRUE)` do not return any complaints about URLs.

**devtools::check(remote = TRUE, manual = TRUE)**
- did not return any significant complaints:

R CMD check results: 
Duration: 1m 16.2s

❯ checking CRAN incoming feasibility ... [5s/19s] NOTE
  Maintainer: ‘John Sakaluk <jksakaluk@gmail.com>’
  
  New submission

0 errors ✔ | 0 warnings ✔ | 1 note ✖

**Comment by omarjcamanto** [comment]
Ran `urlchecker::url_check()` and received zero complaints. 

<img width="352" alt="image" src="https://github.com/jsakaluk/dySEM/assets/124099458/d1d2bd92-d432-44e7-bcba-1fb52e935fff">

On Mac and Windows, ran:
`devtools::check()`
`devtools::check(remote = TRUE, manual = TRUE)`
`devtools::check(args = c("--no-manual", "--as-cran"))`

All checks passed. Only `devtools::check(remote = TRUE, manual = TRUE)` returned an unimportant complaint (i.e., note) - see image below:
<img width="468" alt="image" src="https://github.com/jsakaluk/dySEM/assets/124099458/4c118120-6e9e-4b55-a1a3-0688dfa34635">

**Comment by jsakaluk** [comment]
We are one CRAN :) https://cran.r-project.org/web/packages/dySEM/index.html
